environment:
  nodejs_version: "15"

branches:
  only:
    - master

image: Visual Studio 2019

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - set path=%programfiles(x86)%\\Microsoft SDKs\TypeScript\4.2;%path%

build_script:
  - npm run vscode:prepublish

test_script:
  - npm run cov

notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/bb4990244c63e96e6cb9
    headers:
      APPVEYOR-PROJECT-NAME: '{{projectName}}'
      APPVEYOR-BUILD-VERSION: '{{buildVersion}}'
      APPVEYOR-COMMIT-ID: '{{commitId}}'
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true
