name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '6.x'
      - run: npm install

      - name: Lint
        run: npm run lint
  
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '6.x'
      - run: npm install

      - name: Compile
        run: npm run compile
  
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # disable ubuntu-latest until https://github.com/microsoft/vscode/issues/106569 is fixed
        os: [macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '6.x'
      - run: npm install

      - name: Test
        run: npm run test
      
      - name: Publish coverage
        run:
          - npm run coverage
          - ./publish_coverage.sh
        if: matrix.os == 'macOS-latest'